spring:
    application:
        name: demo

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./build/h2db/db/demo;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE;MODE=MySQL;NON_KEYWORDS=user,value,end
        username: demo
        password:
